### PR TITLE
Use the base URI specified by a `<base>` element.

### PR DESCRIPTION
**Pull request by jonathanj**
[Review on Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/28)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/documint/render/flying_saucer.clj, line 14 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/28#-KA4ivIQVqIeO8guszr5:-KA4ivIR--E13LwBoRMY:-1540334180) ([raw file](https://github.com/fusionapp/clj-documint/blob/493f515965c69a3e9ebaa335b089ade2665f6377/src/documint/render/flying_saucer.clj#L14)):*
This logic is slightly incorrect, since if there's no `<base>` in `<head>`, it might find one elsewhere. However, that's invalid markup, so I don't really think it's worth worrying about.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/28)*

**Comment by jonathanj** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/documint/render/flying_saucer.clj, line 14 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/28#-KA4ivIQVqIeO8guszr5:-KA4lxCY7nqbmnj74KVg:195916635) ([raw file](https://github.com/fusionapp/clj-documint/blob/493f515965c69a3e9ebaa335b089ade2665f6377/src/documint/render/flying_saucer.clj#L14)):*
I did think about this but figured that it's possibly not really worth adding the extra complexity for.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/28)*

**Comment by jonathanj** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/28)*

**Comment by jonathanj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/documint/render/flying_saucer.clj, line 14 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/28#-KA4ivIQVqIeO8guszr5:-KA4mZrRhug-9hlgSezJ:-499146009) ([raw file](https://github.com/fusionapp/clj-documint/blob/493f515965c69a3e9ebaa335b089ade2665f6377/src/documint/render/flying_saucer.clj#L14)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/28)*

**Comment by jonathanj** [comment]
Fixes #25.

**Pull request merged**
