### PR TITLE
Add Prometheus metrics / instrumentation

### PR DESCRIPTION
**Pull request by mithrandi**
This change is [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/81)

### CODE REVIEW

**Comment by jonathanj** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build.boot, line 4 at r1](https://reviewable.io:443/reviews/fusionapp/clj-documint/81#-Ky_KIK18aZE1QZKHbc2:-Ky_KIK18aZE1QZKHbc3:b3fjoux) ([raw file](https://github.com/fusionapp/clj-documint/blob/2f2f089ed781d5e5c0c3b8ed88273c2f9c4e25f0/build.boot#L4)):*
> ```Clojure
>  :resource-paths #{"src"}
>  :dependencies '[[org.clojure/clojure "1.8.0"]
>                  [danielsz/boot-environ "0.0.5"]
> ```

If you're going to remove this, you probably need to remove the `require` a bit later in the boot file.

---

*[src/documint/actions.clj, line 53 at r1](https://reviewable.io:443/reviews/fusionapp/clj-documint/81#-Ky_hScQvb_GUQ5Vz_zY:-Ky_hScQvb_GUQ5Vz_zZ:b-cdfq4l) ([raw file](https://github.com/fusionapp/clj-documint/blob/de3a12df527ecaeaaae049617e63247739ce6e87/src/documint/actions.clj#L53)):*
> ```Clojure
>   (if-let [action (get known-actions action-name)]
>     (try
>       (prometheus/with-duration
> ```

These won't handle asynchronous success/failure very well, as discussed on Slack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/81)*

**Comment by jonathanj** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/documint/actions.clj, line 57 at r2](https://reviewable.io:443/reviews/fusionapp/clj-documint/81#-KyuM3L953WdLEYZVu-b:-KyuM3L953WdLEYZVu-c:blaucup) ([raw file](https://github.com/fusionapp/clj-documint/blob/8c249a765441808d388b175984bbed8496968a5e/src/documint/actions.clj#L57)):*
> ```Clojure
>       (registry :documint/actions-errored-total {:action action-name})
>       (try
>         (->>
> ```

Manifold's functions all generally take the deferred as the first arg, not the last. It seems a bit odd to mix these like this, especially since it makes combining the metrics functions with ordinary manifold operations awkward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/81)*

**Comment by mithrandi** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[build.boot, line 4 at r1](https://reviewable.io:443/reviews/fusionapp/clj-documint/81#-Ky_KIK18aZE1QZKHbc2:-Kyv9530ezJyeARKt_pm:b-imz8n9) ([raw file](https://github.com/fusionapp/clj-documint/blob/2f2f089ed781d5e5c0c3b8ed88273c2f9c4e25f0/build.boot#L4)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

If you're going to remove this, you probably need to remove the `require` a bit later in the boot file.
</blockquote></details>

This was unintentional, I reverted it.

---

*[src/documint/actions.clj, line 57 at r2](https://reviewable.io:443/reviews/fusionapp/clj-documint/81#-KyuM3L953WdLEYZVu-b:-Kyv98AEmEwF77Xsz73z:b-9vhulw) ([raw file](https://github.com/fusionapp/clj-documint/blob/8c249a765441808d388b175984bbed8496968a5e/src/documint/actions.clj#L57)):*
<details><summary><i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary><blockquote>

Manifold's functions all generally take the deferred as the first arg, not the last. It seems a bit odd to mix these like this, especially since it makes combining the metrics functions with ordinary manifold operations awkward.
</blockquote></details>

I swapped it around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/81)*

**Comment by jonathanj** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/81)*

**Comment by jonathanj** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/81#-:-KyvmJHNIRk8cRCVi_EN:b-ydi9ay)*

**Pull request merged**
