### PR TITLE
Improve the README and documentation.

### LINKED ISSUE #90: Improve README
A more informative README would be nice.

### PR DESCRIPTION
**Pull request by jonathanj**
This also includes a Drone task to build and publish documentation to
<https://fusionapp.github.io/clj-documint/>.

Fixes #90.

---
This change is [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/91)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @jonathanj)

---

*[.drone.yml, line 42 at r1](https://reviewable.io/reviews/fusionapp/clj-documint/91#-LFW_qd4EiCSuJyi8L_w:-LFW_qd4EiCSuJyi8L_x:bms8w37) ([raw file](https://github.com/fusionapp/clj-documint/blob/f30e1860e9dc4db3c79713509ec875ab0f243dc0/.drone.yml#L42)):*
> ```YAML
>         - pull-request
>         - tag
>   publish_docs:
> ```

I think this should go after `rebuild_cache`.

---

*[doc/setup.md, line 15 at r1](https://reviewable.io/reviews/fusionapp/clj-documint/91#-LFWaDL62UzHWtHCdF34:-LFWaDL62UzHWtHCdF35:b-1j36ab) ([raw file](https://github.com/fusionapp/clj-documint/blob/f30e1860e9dc4db3c79713509ec875ab0f243dc0/doc/setup.md#L15)):*
> ```Markdown
>   * Copy `documint.config.json.example` to `documint.config.json` and adjust the
>     configuration to suit your environment. (See below for setting up the keystore
>     and truststore if neccessary.)
> ```

Too many `c`

---


*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/91)*

**Comment by jonathanj** [comment]
Review status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @mithrandi)

---

*[.drone.yml, line 42 at r1](https://reviewable.io/reviews/fusionapp/clj-documint/91#-LFW_qd4EiCSuJyi8L_w:-LFWbBw51JxeLb5hHyFt:b-896fix) ([raw file](https://github.com/fusionapp/clj-documint/blob/f30e1860e9dc4db3c79713509ec875ab0f243dc0/.drone.yml#L42)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary><blockquote>

I think this should go after `rebuild_cache`.
</blockquote></details>

Done.

---

*[doc/setup.md, line 15 at r1](https://reviewable.io/reviews/fusionapp/clj-documint/91#-LFWaDL62UzHWtHCdF34:-LFWbgFHCc5rRK1y2csX:bs7wunb) ([raw file](https://github.com/fusionapp/clj-documint/blob/f30e1860e9dc4db3c79713509ec875ab0f243dc0/doc/setup.md#L15)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary><blockquote>

Too many `c`
</blockquote></details>

Done..

---


*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/91)*

**Comment by mithrandi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jonathanj)

---

*[.drone.yml, line 40 at r2](https://reviewable.io/reviews/fusionapp/clj-documint/91#-LFWch_y8eI0KKXcw9sA:-LFWch_y8eI0KKXcw9sB:b-bg5mju) ([raw file](https://github.com/fusionapp/clj-documint/blob/d1c24426ef688976ab3778efa006b25a442b8ecb/.drone.yml#L40)):*
> ```YAML
>       event:
>         - push
>         - pull-request
> ```

This should be `pull_request`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/91)*

**Comment by jonathanj** [comment]
Review status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @mithrandi)

---

*[.drone.yml, line 40 at r2](https://reviewable.io/reviews/fusionapp/clj-documint/91#-LFWch_y8eI0KKXcw9sA:-LFWdkVK8D_B0teNlRdd:b-896fix) ([raw file](https://github.com/fusionapp/clj-documint/blob/d1c24426ef688976ab3778efa006b25a442b8ecb/.drone.yml#L40)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary><blockquote>

This should be `pull_request`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/91)*

**Comment by mithrandi** [comment]
bors r+

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/91#-:-LFWfinX1v4RGD7txbZ0:b-ydi9ay)*

**Pull request merged**
