### PR TITLE
Add a Dockerfile.

### LINKED ISSUE #30: Dockerfile

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #30.

[Review on Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/31)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 3 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/31#-KAAdOrK3EUwZVTps5OY:-KAAdOrK3EUwZVTps5OZ:146008659) ([raw file](https://github.com/fusionapp/clj-documint/blob/2160ec674efe22b24d43fe7a344a01249e62b639/Dockerfile#L3)):*
You can make the image smaller by adding `&& rm -rf /var/lib/apt/lists/*` to the end of this invocation (we should probably be doing that everywhere).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/31)*

**Comment by jonathanj** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 3 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/31#-KAAdOrK3EUwZVTps5OY:-KAAj7rNuRd0NKBUADMz:-499146009) ([raw file](https://github.com/fusionapp/clj-documint/blob/2160ec674efe22b24d43fe7a344a01249e62b639/Dockerfile#L3)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/31)*

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/31)*

**Comment by jonathanj** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/clj-documint/31)*

**Pull request merged**
