### PR TITLE
Introduce a `render-legacy-html` action that uses CSS2XSLFO and Apache FOP.

### LINKED ISSUE #94: Legacy (CSS2XSLFO+FOP) HTML renderer
This would allow us to retire (py)documint altogether and has the advantage of not spinning up a new JVM for every document render.

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #94.

---
This change is [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/95)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 32 of 32 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/95)*

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/95)*

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/95)*

**Comment by jonathanj** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/95#-:-LGPUTmcEnz2EMSbrl2Y:b-ydi9ay)*

**Pull request merged**
