### PR TITLE
Render page thumbnails more efficiently.

### LINKED ISSUE #52: Iterate thumbnails more efficiently
Currently we create thumbnail bitmaps for every page first and then write them out in the action thunks, meaning we need to hold all these bitmaps in memory before writing them out. Since realising the thunks is parallelised anyway, we might as well generate the thumbnail in the thunk.

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #52.

---
This change is [Reviewable](https://reviewable.io/reviews/fusionapp/clj-documint/53)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/53)*

**Comment by mithrandi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/documint/pdf.clj, line 89 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/53#-KGIIlQWdfTLKj-hoMks:-KGIIlQWdfTLKj-hoMkt:1712782863) ([raw file](https://github.com/fusionapp/clj-documint/blob/495aefb6b2e1075a92cca862cda2ff2c642337bb/src/documint/pdf.clj#L89)):*
I think the `:builtin` thread pool here that's used is the "send-off" pool which grows infinitely: this isn't great. Instead, we should have our own thread pool sized by `(claypoole/ncpus)`. I'm not really sure what the best way to have a "service-global" pool is; obviously we could just have a completely global `(def)`, but if you can create it and pass it down, that would probably be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/53)*

**Comment by jonathanj** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/documint/pdf.clj, line 89 \[r1\]](https://reviewable.io:443/reviews/fusionapp/clj-documint/53#-KGIIlQWdfTLKj-hoMks:-KGRnWeK-JotoNhh241h:487125342) ([raw file](https://github.com/fusionapp/clj-documint/blob/495aefb6b2e1075a92cca862cda2ff2c642337bb/src/documint/pdf.clj#L89)):*
I opted just for a private global here. I suspect that improving modularity here might involve deeper changes than we want to introduce at this point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/53)*

**Comment by mithrandi** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fusionapp/clj-documint/53)*

**Pull request merged**
